blueprints/blog.py
from flask import Blueprint, render_template, request, jsonify, session, g, url_for, redirect
from exts import db
from models import BlogModel, UserModel, BlogLikesModel, BlogCollectionModel, CommentModel, QuestionModel
from decorators import login_required
from .forms import AnswerForm


bp = Blueprint('blog', __name__, url_prefix='/blog')


@bp.route("/", methods=['GET', 'POST'])
def blog_index():
    blogs = BlogModel.query.order_by(db.text("-create_time")).all()
    return render_template("blogbase.html", blogs=blogs)


@bp.route("/<int:blog_id>")
def blog_detail(blog_id):
    blog = BlogModel.query.get(blog_id)
    username = session.get('username')
    user = UserModel.query.filter(UserModel.username == username).first()
    # return render_template("detail.html", question=question)
    return render_template('blog_detail.html', blog=blog, user=user)

@bp.route('/like')
def blog_like():
    blog_id_ = request.args.get('bid')
    tag = request.args.get('id')
    username = session.get('username')
    user = UserModel.query.filter(UserModel.username == username).first()
    blog_ = BlogModel.query.get(blog_id_)
    blog_like_ = BlogLikesModel.query.filter(BlogLikesModel.user == user.id, BlogLikesModel.blog == blog_.id).first()
    if tag == '1' and blog_like_:
        blog_.likes -= 1
        db.session.delete(blog_like_)
    elif tag == '0' and (blog_like_ is None):
        blog_.likes += 1
        new_likes = BlogLikesModel(user=user.id, blog=blog_.id)
        db.session.add(new_likes)
    db.session.commit()
    return jsonify(num=blog_.likes)


@bp.route('/collect')
def blog_collection():
    blog_id = request.args.get('bid')
    tag = request.args.get('id')
    username = session.get('username')
    user = UserModel.query.filter(UserModel.username == username).first()
    blog_ = BlogModel.query.get(blog_id)
    blog_collection_ = BlogCollectionModel.query.filter(BlogCollectionModel.user == user.id, BlogCollectionModel.blog == blog_.id).first()
    if tag == '3' and blog_collection_:
        blog_.collects -= 1
        db.session.delete(blog_collection_)
    elif tag == '2' and (blog_collection_ is None):
        blog_.collects += 1
        new_collection = BlogCollectionModel(user=user.id, blog=blog_.id)
        db.session.add(new_collection)
    db.session.commit()
    return jsonify(num_=blog_.collects)


@bp.route("/comment/<int:blog_id>", methods=['POST'])
@login_required
def comment(blog_id):
    form = AnswerForm(request.form)
    if form.validate():
        blog = BlogModel.query.get(blog_id)
        content = form.content.data
        answer_model = CommentModel(content=content, author=g.user, blog_id=blog_id)
        db.session.add(answer_model)
        blog.comments += 1
        db.session.commit()
        # question = QuestionModel.query.get(question_id)
        # print(question.comments)
        # comment_ = int(question.comments) + 1
        # cursor.execute("update question set comments=%d where question_id=%d" % (comment_, question_id))
        # conn.commit()
        return redirect(url_for("blog.blog_detail", blog_id=blog_id))
    else:
        return redirect(url_for("blog.blog_detail", blog_id=blog_id))

blueprints/qa.py
from flask import Blueprint, render_template, request, g, redirect, url_for, flash, jsonify, session
from decorators import login_required
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel, UserModel
from exts import db
from sqlalchemy import or_

bp = Blueprint('qa', __name__, url_prefix='/')


@bp.route("/")
def index():
    questions = QuestionModel.query.order_by(db.text("-create_time")).all()
    hot_questions = QuestionModel.query.order_by(QuestionModel.comments.desc()).limit(5)
    return render_template("bbs.html", questions=questions, hot_questions=hot_questions)


@bp.route("/question/publish", methods=['GET', 'POST'])
@login_required
def publish_question():
    # 判断是否登录，如果没有登录，跳转到登录页面
    if request.method == 'GET':
        hot_questions = QuestionModel.query.order_by(QuestionModel.comments.desc()).limit(5)
        return render_template("publish_question.html", hot_questions=hot_questions)
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            flash("已发布一条匿名帖！")
            return redirect("/")
        else:
            hot_questions = QuestionModel.query.order_by(QuestionModel.comments.desc()).limit(5)
            flash("标题或内容格式错误！")
            return redirect(url_for("qa.publish_question", hot_questions=hot_questions))


@bp.route("/question/<int:question_id>")
def question_detail(question_id):
    hot_questions = QuestionModel.query.order_by(QuestionModel.comments.desc()).limit(5)
    question = QuestionModel.query.get(question_id)
    return render_template('detail.html', question=question, hot_questions=hot_questions)


@bp.route("/answer/<int:question_id>", methods=['POST'])
@login_required
def answer(question_id):
    form = AnswerForm(request.form)
    if form.validate():
        hot_questions = QuestionModel.query.order_by(QuestionModel.comments.desc()).limit(5)
        question = QuestionModel.query.get(question_id)
        content = form.content.data
        answer_model = AnswerModel(content=content, author=g.user, question_id=question_id)
        db.session.add(answer_model)
        question.comments += 1
        db.session.commit()
        return redirect(url_for("qa.question_detail", question_id=question_id, hot_questions=hot_questions))
    else:
        hot_questions = QuestionModel.query.order_by(QuestionModel.comments.desc()).limit(5)
        # flash("表单验证失败！")
        return redirect(url_for("qa.question_detail", question_id=question_id, hot_questions=hot_questions))


@bp.route("/search")
def search():
    # /search?q=xxx
    q = request.args.get("q")
    # filter_by：直接使用字段的名称
    # filter：使用模型.字段名称
    questions = QuestionModel.query.filter(
        or_(QuestionModel.title.contains(q), QuestionModel.content.contains(q))).order_by(db.text("-create_time"))
    return render_template("homepage.html", questions=questions)


@bp.route("reply/<int:answer_id>", methods=['GET', 'POST'])
@login_required
def reply(answer_id):
    if request.method == 'GET':
        answer_ = AnswerModel.query.get(answer_id)
        return render_template("reply.html", answer_id=answer_id, answer=answer_)
    else:
        form = AnswerForm(request.form)
        answer_ = AnswerModel.query.get(answer_id)
        question = QuestionModel.query.filter(QuestionModel.id == answer_.question_id).first()
        if form.validate():
            content = "回复[" + str(answer_id) + "]>> " + form.content.data
            reply_ = AnswerModel(question_id=question.id, content=content, author_id=g.user.id)
            db.session.add(reply_)
            db.session.commit()
            flash("回复成功！")
            return redirect(url_for("qa.question_detail", question_id=question.id))
        else:
            flash("内容格式错误！请至少输入1个字符。")
            # return redirect(url_for("qa.reply", answer_id=answer_id, answer=answer_))
            return render_template("reply.html", answer_id=answer_id, answer=answer_)



# @bp.route('/like')
# def answer_like():
#     answer_id_ = request.args.get('bid')
#     tag = request.args.get('id')
#     username = session.get('username')
#     user = UserModel.query.filter(UserModel.username == username)
#     answer_ = AnswerModel.query.get(answer_id_)
#     answer_like_ = CommentLikeModel.query.filter(CommentLikeModel.user == user.id, CommentLikeModel.answer == answer_.id).first()
#     if tag == '1' and answer_like_:
#         answer_.likes -= 1
#         db.session.delete(answer_like_)
#     elif tag == '0' and (answer_like_ is None):
#         answer_.likes += 1
#         new_likes = CommentLikeModel(user=user.id, answer=answer_.id)
#         db.session.add(new_likes)
#     db.session.commit()
#     return jsonify(numb=answer_.likes)

blueprints/user.py
from flask import Blueprint, render_template, jsonify, request, url_for, session, flash, redirect, g
from exts import mail, db
from flask_mail import Message
from models import EmailCaptchaModel, UserModel, QuestionModel, BlogModel, BlogCollectionModel, FollowModel
from datetime import datetime
import string
import random
from .forms import RegisterForm, LoginForm,changeForm
from werkzeug.security import generate_password_hash, check_password_hash
from werkzeug.utils import secure_filename
from decorators import login_required
import time, os, uuid
from datetime import timedelta


bp = Blueprint('user', __name__, url_prefix='/user')


@bp.route("/login", methods=['GET', 'POST'])
def login():
    if request.method == 'GET':
        return render_template("sign-in.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.id
                session['username'] = user.username
                return redirect("/")
            else:
                flash("邮箱和密码不匹配！")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱或密码格式错误！")
            return redirect(url_for("user.login"))


@bp.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'GET':
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            letters = string.digits + string.ascii_letters
            email = form.email.data
            password = form.password.data
            username = form.username.data
            hash_password = generate_password_hash(password)
            nickname = ''.join(random.sample(letters, 10))
            user = UserModel(email=email, password=hash_password, username=username, nickname=nickname)
            db.session.add(user)
            db.session.commit()
            flash("注册成功！")
            return redirect(url_for("user.login"))
        else:
            flash("注册失败，请重试。注意格式要符合要求哦，并且确保邮箱用户名未被注册过。")
            return redirect(url_for("user.register"))


@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('user.login'))

@bp.route("/captcha", methods=['POST', 'GET'])
def get_captcha():
    email = request.form.get("email")
    letters = string.digits
    captcha = "".join(random.sample(letters, 6))
    if email:
        message = Message(
            subject="验证码",
            recipients=[email],
            body=f"[匿名墙]您的注册验证码是：{captcha}，您正在登录匿名讨论板账号，若非本人操作，请忽略此邮件。"
        )
        mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        # print("captcha:", captcha)
        # code: 200，成功的、正常的请求
        return jsonify({"code": 200})
    else:
        # code：400，客户端错误
        return jsonify({"code": 400}, {"message": "请先传递邮箱！"})


@bp.route("/myBlog")
@login_required
def myBlog():
    username = session.get('username')

    user = UserModel.query.filter(UserModel.username == username).first()
    # order_by按照时间倒序
    questionList = QuestionModel.query.filter(QuestionModel.author_id == user.id).order_by(QuestionModel.create_time.desc()).limit(3).all()
    blogList = BlogModel.query.filter(BlogModel.author_id == user.id).order_by(BlogModel.create_time.desc()).all()
    collected = BlogCollectionModel.query.filter(BlogCollectionModel.user == user.id).order_by(BlogCollectionModel.create_time.desc()).all()
    collected_blog = []
    for collection in collected:
        collect = None
        if collection is not None:
            collect = BlogModel.query.filter(collection.blog == BlogModel.id)
        collected_blog.append(collect[0])
    followList1 = FollowModel.query.filter(FollowModel.follower_id == user.id).order_by(FollowModel.create_time.desc()).all()
    followedList = []
    for follow1 in followList1:
        followed = UserModel.query.filter(UserModel.id == follow1.followed_id)
        followedList.append(followed[0])
    followList2 = FollowModel.query.filter(FollowModel.followed_id == user.id).order_by(FollowModel.create_time.desc()).all()
    followerList = []
    for follow2 in followList2:
        follower = UserModel.query.filter(UserModel.id == follow2.followed_id)
        followerList.append(follower[0])
    return render_template("myBlog.html", blogList=blogList, user=user, questionList=questionList, collected_blog=collected_blog
                           , followedList=followedList, followerList=followerList)

# 设置允许的文件格式
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'JPG', 'PNG', 'bmp'])
def allowed_file(filename):
    return '.' in filename and filename.rsplit('.', 1)[1] in ALLOWED_EXTENSIONS

# 设置静态文件缓存过期时间
bp.send_file_max_age_default = timedelta(seconds=20)


@bp.route('/change_idiom', methods=['POST', 'GET'])
@login_required
def change_idiom():
    username = session.get('username')
    user = UserModel.query.filter(UserModel.username == username).first()
    form = changeForm(request.form)
    user.idiom = form.idiom.data
    db.session.commit()
    return redirect(url_for("user.myBlog"))\



# 上传照片
@bp.route('/upload', methods=['POST', 'GET'])
@login_required
def upload():
    if request.method == 'POST':
        # 通过file标签获取文件
        f = request.files['file']
        if not (f and allowed_file(f.filename)):
            return jsonify({"error": 1001, "msg": "图片类型：png、PNG、jpg、JPG、bmp"})
        # 当前文件所在路径
        basepath = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        # 一定要先创建该文件夹，不然会提示没有该路径
        upload_path = os.path.join(basepath, '/static/uploadImg', secure_filename(f.filename))
        # 保存文件
        filename = 'user'+str(g.user.id) + '.' + f.filename.rsplit('.', 1)[1]
        file_path = os.path.join(basepath, 'static', 'uploadImg', filename)
        f.save(file_path)
        print(filename)
        g.user.gravatar = '../static/uploadImg/' + filename
        db.session.commit()
        # 返回上传成功界面
        return redirect(url_for("user.myBlog"))


# md编辑器上传图片
@bp.route('/imgUpload', methods=['POST'])
@login_required
def imgUpload():
    try:
        file = request.files.get('editormd-image-file');
        fname = secure_filename(file.filename);
        ext = fname.rsplit('.')[-1];
        # 生成一个uuid作为文件名
        fileName = str(uuid.uuid4()) + "." + ext;
        filePath = os.path.join("static/uploadImg/", fileName);
        file.save(filePath)
        return {
            'success': 1,
            'message': '上传成功!',
            'url': "/" + filePath
        }
    except Exception:
        return {
            'success': 0,
            'message': '上传失败'
        }


# 写博客页面
@bp.route('/writeBlog', methods=['POST', 'GET'])
@login_required
def writeblog():
    if request.method == 'GET':
        return render_template('writeBlog.html')
    if request.method == 'POST':
        title = request.form.get("title")
        text = request.form.get("text")
        username = session.get('username')
        create_time = time.strftime("%Y-%m-%d %H:%M:%S")
        user = UserModel.query.filter(UserModel.username == username).first()
        blog = BlogModel(title=title, content=text, create_time=create_time, author_id=user.id)
        db.session.add(blog)
        db.session.commit()
        blog = BlogModel.query.filter(BlogModel.create_time == create_time).first()
        return render_template('blogSuccess.html', title=title, id=blog.id, user=user)


@bp.route('/follow')
@login_required
def follow():
    author_id_ = request.args.get('bid')
    tag = request.args.get('id')
    username = session.get('username')
    user = UserModel.query.filter(UserModel.username == username).first()
    author_ = UserModel.query.get(author_id_)
    author_follow_ = FollowModel.query.filter(FollowModel.follower_id == user.id, FollowModel.followed_id == author_.id).first()
    if tag == '1' and author_follow_:
        author_.followed -= 1
        user.follow -= 1
        db.session.delete(author_follow_)
        db.session.commit()
        return jsonify(num="未关注")
    elif tag == '0' and (author_follow_ is None):
        author_.followed += 1
        user.follow += 1
        new_follows = FollowModel(follower_id=user.id, followed_id=author_.id)
        db.session.add(new_follows)
        db.session.commit()
        return jsonify(num="已关注")

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description"
          content="Probably the most complete UI kit out there. Multiple functionalities and controls added,  extended color palette and beautiful typography, designed as its own extended version of Bootstrap at  the highest level of quality.                             ">
    <meta name="author" content="ustcflask">
    <title>{% block title %}{{ title|default }}{% endblock title %}</title>
    <!-- Fonts -->
    <!-- Plugins -->
    <link rel="stylesheet" href="../static/vendor/animate/animate.min.css" type="text/css">
    <!-- Theme CSS -->
    <link type="text/css" href="../static/css/theme.css" rel="stylesheet">
    <!-- Demo CSS - No need to use these in your project -->
    <link rel="stylesheet" href="../static/vendor/jquery-scrollbar/css/jquery-scrollbar.css">
    <link type="text/css" href="../static/vendor/highlight/css/highlight.min.css" rel="stylesheet">
    <link type="text/css" href="../static/css/demo.css" rel="stylesheet">
    <link rel="stylesheet" href="../static/layui/css/layui.css">
    <script src="../static/js/jquery.js"></script>
    <script src="../static/layui/layui.js"></script>
    <script src="{{ url_for('static',filename='jquery/jquery.3.6.min.js') }}"></script>
    <script src="{{ url_for('static',filename='js/register.js') }}"></script>
    {% block css %}
    {% endblock %}
</head>
<body>
<main class="main">
    <aside class="sidebar" style="background: #F5F6F7" id="nav_docs">
        <div class="sidebar-brand">
            <h1 class="font-weight-400">
                <a href="/">
                    <span class="font-weight-900">USTC</span> 匿名讨论板</a>
            </h1>
        </div>
        <div class="scrollbar-inner scroll-content scroll-scrolly_visible"
             style="height: auto; margin-bottom: 0px; margin-right: 0px; max-height: 422.4px;">
            <ul class="navigation pr-3">
                <li class="navigation-title"><strong>USTC</strong> 匿名讨论板</li>
                <li class="navigation-item">
                    <a href="/" class="navigation-link">实时</a>
                </li>
                <li class="navigation-item">
                    <a href="/hot" class="navigation-link">热榜(hot!)</a>
                </li>
                <li class="navigation-title">
                    <strong>USTC</strong> 博客园
                </li>
                <li class="navigation-item">
                    <a href="{{ url_for('blog.blog_index') }}" class="navigation-link">实时</a>
                </li>
                {#                <li class="navigation-item">#}
                {#                    <a href="{{ url_for('blog.blog_hot') }}" class="navigation-link">热榜（/hot）</a>#}
                {#                </li>#}
            </ul>
        </div>
    </aside>
    <section class="content">
        <div class="header">
            <div class="navigation-trigger d-xl-none" data-action="aside-open" data-target=".sidebar">
                <div class="navigation-trigger-inner">
                    <i class="navigation-trigger-line"></i>
                    <i class="navigation-trigger-line"></i>
                    <i class="navigation-trigger-line"></i>
                </div>
            </div>
            <div class="header-brand d-xl-none">
                <h1><a href="/">USTC 匿名讨论板</a></h1>
            </div>
            <div class="header-nav ml-auto">
                <ul class="nav align-items-center">
                    <li class="nav-item ml-2">
                        <a href='{{ url_for("qa.index") }}'
                           class="btn btn-sm btn-primary">匿名讨论板</a>
                    </li>
                    <li class="nav-item ml-2">
                        <a href='{{ url_for("blog.blog_index") }}'
                           class="btn btn-sm btn-primary">科大博客园</a>
                    </li>
                    <li class="nav-item ml-2">
                        <a href='{{ url_for("qa.publish_question") }}'
                           class="btn btn-sm btn-primary">发布帖子</a>
                    </li>
                    <li class="nav-item ml-2">
                        <a href="{{ url_for('user.writeblog') }}"
                           class="btn btn-sm btn-primary">写博客</a>
                    </li>
                    {% if g.user %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbar_main_dropdown_1"
                               role="button" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">{{ user.username }}</a>
                            <div class="dropdown-menu" aria-labelledby="navbar_1_dropdown_1">
                                <a class="dropdown-item" href={{ url_for("user.myBlog") }}>个人中心</a>
                            </div>
                        </li>

                        <li class="nav-item ml-2">
                            <a class="nav-link" href={{ url_for('user.logout') }}>退出登录</a>
                        </li>
                    {% else %}
                        <li class="nav-item ml-2">
                            <a href='{{ url_for("user.login") }}'
                               class="btn btn-sm bg-light">登录</a>
                        </li>
                        <li class="nav-item ml-2">
                            <a href='{{ url_for("user.register") }}'
                               class="btn btn-sm bg-light">注册</a>
                        </li>
                    {% endif %}
                    <li class="nav-item ml-2">
                        <a class="nav-link" href={{ url_for('docs') }}>文档</a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="content-inner content-docs">

            <div class="container">
                <div class="row">
                    <div class="col-lg-9">
                        {% block content %}

                        {% endblock content %}
                        {% block content_ %}

                        {% endblock content_ %}
                        {% block content__ %}

                        {% endblock content__ %}
                    </div>
                    <div class="col-lg-3 d-none d-lg-inline-block">
                        <div class="sidebar-sticky" data-stick-in-parent="true">
                            <div class="text-center" style="padding-bottom: 10px">
                                <strong>大家都在看：</strong>
                            </div>
                            <ul class="section-nav">
                                {% for question in hot_questions %}
                                <li class="toc-entry toc-h3"><a href="/question/{{ question.id }}">{{ question.title }}</a></li>
                                {% endfor %}
                            </ul>
                            <div class="text-center" style="padding-top: 20px">
                                <button type="button" class="btn btn-outline-primary btn-animated btn-animated-x">
                                    <a class="btn-inner--visible" href="#top">回到顶部</a>
                                    <a class="btn-inner--hidden text-white" href="#top"><i class="fas fa-arrow-up"></i></a>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {% block footer -%}
            <footer class="pt-5 pb-3 footer" style="background: #F5F6F7">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-md-4">
                            <div class="pr-lg-5">
                                <h1 class="heading h6 text-uppercase font-weight-700 mb-3"><strong>中国科大</strong>
                                    匿名讨论板</h1>
                                <p> 欢迎！</p>
                            </div>
                        </div>
                        <div class="col-6 col-md">
                            <h5 class="heading h6 text-uppercase font-weight-700 mb-3">关于我们</h5>
                            <ul class="list-unstyled text-small">
                                <li><a class="text-muted" href={{ url_for('aboutus') }}>成员简介</a></li>
                            </ul>
                        </div>
                    </div>
                    <hr>
                    <div class="d-flex align-items-center">
          <span class="">
            &copy; 2022 <a href="https://webpixels.io/" class="footer-link" target="_blank">ustcflask</a>. All rights reserved.
          </span>
                        <ul class="nav ml-lg-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="https://github.com/ustcflask/dyk_trial" target="_blank"><i
                                        class="fab fa-github"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </footer>
        {%- endblock footer %}
    </section>
</main>
<!-- Core -->
<script src="../static/vendor/jquery/jquery.min.js"></script>
<script src="../static/vendor/popper/popper.min.js"></script>
<script src="../static/js/bootstrap/bootstrap.min.js"></script>
<!-- FontAwesome 5 -->
<script src="../static/vendor/fontawesome/js/fontawesome-all.min.js" defer></script>
<!-- Scripts used only for this demo only - Remove these in your project -->
<script src="../static/vendor/jquery-scrollbar/js/jquery-scrollbar.min.js"></script>
<script src="../static/vendor/jquery-scrollLock/jquery-scrollLock.min.js"></script>
<script src="../static/vendor/sticky-kit/sticky-kit.min.js"></script>
<script src="../static/vendor/highlight/js/highlight.min.js"></script>
<script src="../static/vendor/clipboard-js/clipboard.min.js"></script>
<script src="../static/vendor/holderjs/holder.min.js"></script>
<script src="../static/js/demo.js"></script>
<!-- Theme JS -->
<script src="../static/js/theme.js"></script>
{% block scripts %}

{% endblock %}
</body>
</html>

templates/upload.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Flask网页上传图片演示</title>
</head>
<body>
    <form action="#" enctype='multipart/form-data' method='POST'>
        <input type="file" name="file" style="margin-top:20px;"/>
        <input type="submit" value="上传" class="button-new" style="margin-top:15px;"/>
    </form>
</body>
</html>